#pragma once

// -----------------------------------------------------------------------------
// Async chunk-generation scheduler
// -----------------------------------------------------------------------------
#if PLATFORM_ASYNC_CHUNK_GENERATION
#  define PLATFORM_ASYNC_GENERATION_QUEUE_LIMIT       PLATFORM_WII_ASYNC_GENERATION_QUEUE_LIMIT
#  define PLATFORM_ASYNC_GENERATION_REQUESTS_PER_TICK PLATFORM_WII_ASYNC_GENERATION_REQUESTS_PER_TICK
#  define PLATFORM_ASYNC_GENERATION_PUBLISH_PER_TICK  PLATFORM_WII_ASYNC_GENERATION_PUBLISH_PER_TICK
#  define PLATFORM_ASYNC_GENERATION_THREAD_PRIORITY   PLATFORM_WII_ASYNC_GENERATION_THREAD_PRIORITY
#  define PLATFORM_ASYNC_GENERATION_REQUESTS_PER_FRAME PLATFORM_WII_ASYNC_GENERATION_REQUESTS_PER_FRAME
#  define PLATFORM_ASYNC_GENERATION_PUBLISH_PER_FRAME  PLATFORM_WII_ASYNC_GENERATION_PUBLISH_PER_FRAME
#else
#  define PLATFORM_ASYNC_GENERATION_QUEUE_LIMIT       0
#  define PLATFORM_ASYNC_GENERATION_REQUESTS_PER_TICK 0
#  define PLATFORM_ASYNC_GENERATION_PUBLISH_PER_TICK  0
#  define PLATFORM_ASYNC_GENERATION_THREAD_PRIORITY   64
#  define PLATFORM_ASYNC_GENERATION_REQUESTS_PER_FRAME 0
#  define PLATFORM_ASYNC_GENERATION_PUBLISH_PER_FRAME  0
#endif
