#pragma once

#include "EnumOS1.h"
#include "java/Type.h"

// net.minecraft.src.OsMap
// In Java this is a synthetic switch-map class generated by the compiler.
// It maps EnumOS1 ordinals to case indices; in C++ we replicate as a lookup array.
class OsMap
{
public:
    // switchMap[ordinal] -> case index (1-4), matching the Java static initializer
    static const int_t switchMap[5]; // indexed by (int)EnumOS1
};
