#include "RenderSquid.h"
#include "EntitySquid.h"
#include "ModelBase.h"
#include "EntityLiving.h"
#include "Entity.h"
#include "MathHelper.h"

RenderSquid::RenderSquid(ModelBase* modelBase, float f) : RenderLiving(modelBase, f) {
}

void RenderSquid::renderSquid(EntitySquid* entitySquid, double d, double d1, double d2, float f, float f1) {
    RenderLiving::doRenderLiving(entitySquid, d, d1, d2, f, f1);
}

void RenderSquid::doRenderLiving(EntityLiving* entityLiving, double d, double d1, double d2, float f, float f1) {
    renderSquid((EntitySquid*)entityLiving, d, d1, d2, f, f1);
}

void RenderSquid::doRender(Entity* entity, double d, double d1, double d2, float f, float f1) {
    renderSquid((EntitySquid*)entity, d, d1, d2, f, f1);
}

void RenderSquid::rotateCorpse(EntityLiving* entityLiving, float f, float f1, float f2) {
    rotateSquidCorpse((EntitySquid*)entityLiving, f, f1, f2);
}

void RenderSquid::rotateSquidCorpse(EntitySquid* entitySquid, float f, float f1, float f2) {
    // Matches Java Beta 1.7.3 RenderSquid.func_21007_a().
    // field_21089_a/field_21088_b = pitch interpolation, applied on X.
    // field_21087_c/field_21086_f = yaw/roll interpolation, applied on Y.
    float f3 = entitySquid->field_21088_b + (entitySquid->field_21089_a - entitySquid->field_21088_b) * f2;
    float f4 = entitySquid->field_21086_f + (entitySquid->field_21087_c - entitySquid->field_21086_f) * f2;
    renderTranslate(0.0f, 0.5f, 0.0f);
    renderRotate(180.0f - f1, 0.0f, 1.0f, 0.0f);
    renderRotate(f3, 1.0f, 0.0f, 0.0f);
    renderRotate(f4, 0.0f, 1.0f, 0.0f);
    renderTranslate(0.0f, -1.2f, 0.0f);
}

float RenderSquid::getTicksExisted(EntityLiving* entityLiving, float partialTicks) {
    // Matches Java Beta 1.7.3 RenderSquid.func_21006_b().
    // Squid tentacles do not use generic ticksExisted. They use the
    // interpolated tentacle angle generated by EntitySquid.
    EntitySquid* squid = static_cast<EntitySquid*>(entityLiving);
    return squid->field_21082_j + (squid->field_21083_i - squid->field_21082_j) * partialTicks;
}
